FROM quay.io/redhat-et/rhel-bootc-tegra:microshift

RUN <<EOF
set -Eeuo pipefail

# Enable EPEL and Ansible AAP repos
dnf config-manager --enable ansible-automation-platform-2.5-for-rhel-9-$(arch)-rpms

# Install packages
dnf install -y flightctl-agent
dnf clean all

# Prepare the system for blueprint customizations
rm -f /etc/flightctl/config.yaml /etc/ostree/auth.json

# SSH authorized keys setup
mkdir -p /etc/ssh/authorized_keys/
semanage fcontext -a -t ssh_home_t "/etc/ssh/authorized_keys(/.*)?"
restorecon -Rf /etc/ssh/authorized_keys
EOF

ADD --chown=root:root root /

RUN <<EOF
set -Eeuo pipefail

# Enable systemd services and sockets
systemctl enable flightctl-agent.service

# Make sure the flightctl-agent is the only one that can apply updates
systemctl mask bootc-fetch-apply-updates.timer

EOF